# GLOBAL CONFIGURATION

spring:
  application.name: book-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/book?createDatabaseIfNotExist=true
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  #jpa: 
  #  hibernate:
  #    ddl-auto: update
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
limit-service:
   username: root
