# GLOBAL CONFIGURATION

spring:
  application.name: config-server-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Hans/Learning/Jpop/config-server
          default-label: main
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

